<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RootNamespace>vortex_secretary_desktop</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MaterialDesignColors" Version="5.2.2-ci976" />
      <PackageReference Include="MaterialDesignThemes" Version="5.2.2-ci976" />
      <PackageReference Include="MySql.Data" Version="9.3.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="teste.png" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Home.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\RequerimentoNovo.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\Template.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\PagDuvidas.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\Duvida.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\PagHistorico.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\Historico.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\RequerimentoEmAndamento.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\PagGerenciamento.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\FormularioWeb.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\RequerimentoNovoExtendido.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\Controls\DuvidaExtendida.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_br.png" />
      <Resource Include="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_br.png" />
      <None Remove="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_cor.ico" />
      <Resource Include="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_cor.ico" />
      <None Remove="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_cor.png" />
      <Resource Include="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_cor.png" />
      <None Remove="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_pb.png" />
      <Resource Include="Views\Imagens\fatec_ra_metropolitana_sp_guarulhos_pb.png" />
    </ItemGroup>

</Project>
